version: '3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/docker/backend/Dockerfile
    networks:
      - django-react
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - django-react
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - django-react
    ports:
      - "6379:6379"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/docker/frontend/Dockerfile
    networks:
      - django-react
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/apps/frontend/node_modules
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: apps/docker/nginx/Dockerfile
    networks:
      - django-react
    ports:
      - "80:80"
    volumes:
      - static:/apps/backend/static

    depends_on:
      - backend
      - frontend
# Networks
networks:
  django-react:
    driver: bridge

volumes:
  db-data:
  node_modules:
  static:
